###########################################################################
############ Tutaj ustawiamy nazwę strony oraz panel nawigacji ############
###########################################################################
site_name: Księgowość Podatkowa Dokumentacja
# rzeczy dodane tutaj pojawią się w górnym panelu 
nav:
# rzeczy dodane tutaj pojawią się w lewy panelu
  - Biuletyn zmian:
    # - Instrukcja Księgowości Podatkowej: Instrukcja Księgowości Podatkowej.md
    - index.md
    - Wersja 3.1.0.19: "#wersja-31019"
    - Wersja 3.1.0.18: "#wersja-31018"
    # - Co nowego?: Co_nowego.md
    # - Elektroniczne tytuły wykonawcze: etw.md
    # - Elektroniczne zawiadomienie wierzyciela: ezw.md
    # - Numer NIP: numernip.md
    # - Format daty wydania orzeczenia: dataworzeczenia.md
    # - Format numeru telefonu: nieprawidlowytelefon.md
    # - Wartość należności pieniężnej: naleznoscp.md
  - Operacje księgowe:
    - operacje_ksiegowe/index.md
    - Wprowadzanie dokumentów BO: operacje_ksiegowe\wprowadzanie_dokumentow_bo.md
    - Księgowanie wpłat: operacje_ksiegowe\ksiegowanie_wplat.md
    - Zwrot nadpłaty: operacje_ksiegowe\zwrot_nadplaty.md
    - Umorzenie zaległości: operacje_ksiegowe\umorzenie_zaleglosci.md
    - Rozłożenie na raty: operacje_ksiegowe\rozlozenie_na_raty.md
    - Cofnięcie rozłożenia na raty: operacje_ksiegowe/cofniecie_rozlozenia.md
    - Przypisy i odpisy do lat ubiegłych: operacje_ksiegowe\przypisy_i_odpisy_do_lat_ubieglych.md
    - Przesunięcie terminu płatności: operacje_ksiegowe\przesuniecie_terminu_platnosci.md
    - Przeksięgowanie sald i nadpłat: operacje_ksiegowe\przeksiegowanie_sald_i_nadplat.md
  - Operacje:
    - operacje/index.md
    - Lista dokumentów: opercje/lista_dokumentow.md
    - Kalkulator odsetkowy: operacje/kalkulator_odsetkowy.md
    - Przeksięgowanie nadpłat i paragrafów: operacje/przeksiegowania.md
    - Dziennik obrotów: operacje/dziennik_obrotow.md
    - Zamnkięcia miesięcy / roku: operacje/zamkniecia.md

  - Import/Export:
    - import-export/index.md
    - Import danych z Wymiaru: import-export/wymiar.md
    - Import wpłat z banku: import-export/bank.md
    - Import wpłat z Kasy: import-export/kasa.md
    - Import wpłat z mObywatela: import-export/mobywatel.md
    - Eksport do systemu FK: import-export/fk.md
  - Upomnienia:
    - upomnienia/index.md
    - Tworzenie upomnienia na koncie użytkownika: upomnienia/Upomnienie_z_konta.md
    - Korespondencja seryjna upomnień: upomnienia/upomnienie_seryjna.md
    - Rejestr upomnień: upomnienia/upomnienie_rejestr.md
  - Egzekucja:
    - egzekucja/index.md
    - Tworzenie tytułu na koncie użytkownika: egzekucja/tytul_wykonawczy.md
    - Korespondencja seryjna tytułów: egzekucja/tytul_seryjna.md
    - Zawiadomienie: egzekucja/zawiadomienie.md
  - Wydruki:
    - wydruki/index.md
    - Rozliczenia: wydruki/rozliczenia.md
    - Obroty na kontach zbiorczych: wydruki/obroty_na_kontach_zbiorczych.md
    - Suma dokumentów: wydruki/suma_dokumentow.md
    - Sprawozdania: wydruki/sprawozdania.md
  - e-Doręczenia:
    - e-doreczenia/index.md
    - Tworzenie e-Doręczeń: e-doreczenia/tworzenie_edoreczen.md
    - Rejestr e-Doręczeń: e-doreczenia/rejestr_edoreczen.md

    
###########################################################################
################ Poniższe można kopiować miedzy projektami ################
###########################################################################
theme: 
  name:  material
  custom_dir: overrides # nadpisane stylu
  language: pl
  logo: assets/logo1_d.png
  icon: #zmiana ikon strzałek w stopce
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    top: fontawesome/solid/angle-up
  features: 
      - navigation.footer
      # - header.autohide
      - navigation.tabs
      # - navigation.sections
      # - toc.integrate
      - navigation.top # przycisk wróć na górę
      - navigation.prune # zmniejsza objętość stron
      # - navigation.path
      - navigation.indexes
      - search.suggest # sugestie w wyszukiwaniu
      - search.highlight
      - search.share
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/brightness-7 
        name: Przełącz na tryb ciemny
    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Przełącz na tryb jasny
extra:
# klikalne logo 
  homepage: https://web.softres.pl/
  generator: false
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
    # poniższe pozwalają na podkreślenia, zaznaczenia tekstu kolorem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # poprawne wyświetlanie list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
copyright: BUK Softres Sp. z o.o. 2023
    # - search.suggest
# use_directory_urls:  false
plugins:
    # wyszukiwarka i jej działanie offline (po zbudowaniu dokumentacji)
    - search
    - offline
    # pozwala na zoom obrazka
    - glightbox
    # odtwarzać wideo
    - mkdocs-video:
        is_video: True
        # video_muted: True
        # video_controls: True
        css_style:
          width: "100%"
extra_css:
  - stylesheets/extra.css


 
 


  
